/*
 * Agravity OpenAPI Documentation - Public Functions
 *
 * <h1>Agravity API Reference</h1>This is the public API description of Agravity GmbH.<br/><h2>Resources</h2><ul> <li>Collection type management</li> <li>Collections management</li> <li>Assets management</li> <li>Assets operations</li> <li>Assets publishing</li> <li>Collection Sharing (consume share)</li> <li>Secure Upload (validate + upload file)</li> <li>Download ZIP</li> <li>Search</li> <li>General management</li></ul><h2> Operations</h2>Agravity API performs the following operations:<ul> <li>List / get single collection types</li> <li>List / get single collections</li> <li>List / get single  assets</li> <li>Operations on assets like: blobs, rotate, resize, similar, collections, customfields, download</li> <li>List / get single published asset</li> <li>Search for assets or collections</li> <li>Get version of deployment</li></ul><br/><b>API key is needed to access these endpoints.</b><br/><br/>Copyright © Agravity GmbH 2022. All Rights Reserved
 *
 * The version of the OpenAPI document: 4.7.1
 * Contact: office@agravity.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using AgravityPublic.Client;
using AgravityPublic.Model;

namespace AgravityPublic.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicTranslationManagementApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        Dictionary<string, Dictionary<string, Object>> HttpTranslationsById (string id, bool? items = default(bool?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdWithHttpInfo (string id, bool? items = default(bool?));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        Dictionary<string, Dictionary<string, Object>> HttpTranslationsByIdFilterByCustomField (string id, string customField);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfo (string id, string customField);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        Dictionary<string, Dictionary<string, Object>> HttpTranslationsByIdFilterByProperty (string id, string property, bool? items = default(bool?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByPropertyWithHttpInfo (string id, string property, bool? items = default(bool?));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdAsync (string id, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdWithHttpInfoAsync (string id, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByCustomFieldAsync (string id, string customField, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync (string id, string customField, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByPropertyAsync (string id, string property, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync (string id, string property, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PublicTranslationManagementApi : IPublicTranslationManagementApi
    {
        private AgravityPublic.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PublicTranslationManagementApi(String basePath)
        {
            this.Configuration = new AgravityPublic.Client.Configuration { BasePath = basePath };

            ExceptionFactory = AgravityPublic.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class
        /// </summary>
        /// <returns></returns>
        public PublicTranslationManagementApi()
        {
            this.Configuration = AgravityPublic.Client.Configuration.Default;

            ExceptionFactory = AgravityPublic.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PublicTranslationManagementApi(AgravityPublic.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = AgravityPublic.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AgravityPublic.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AgravityPublic.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AgravityPublic.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        public Dictionary<string, Dictionary<string, Object>> HttpTranslationsById (string id, bool? items = default(bool?))
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = HttpTranslationsByIdWithHttpInfo(id, items);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        public ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdWithHttpInfo (string id, bool? items = default(bool?))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsById");

            var localVarPath = "/translations/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (items != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "items", items)); // query parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdAsync (string id, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = await HttpTranslationsByIdWithHttpInfoAsync(id, items, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdWithHttpInfoAsync (string id, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsById");

            var localVarPath = "/translations/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (items != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "items", items)); // query parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        public Dictionary<string, Dictionary<string, Object>> HttpTranslationsByIdFilterByCustomField (string id, string customField)
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = HttpTranslationsByIdFilterByCustomFieldWithHttpInfo(id, customField);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        public ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfo (string id, string customField)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            // verify the required parameter 'customField' is set
            if (customField == null)
                throw new ApiException(400, "Missing required parameter 'customField' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");

            var localVarPath = "/translations/{id}/custom/{customField}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (customField != null) localVarPathParams.Add("customField", this.Configuration.ApiClient.ParameterToString(customField)); // path parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsByIdFilterByCustomField", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByCustomFieldAsync (string id, string customField, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = await HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync(id, customField, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync (string id, string customField, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            // verify the required parameter 'customField' is set
            if (customField == null)
                throw new ApiException(400, "Missing required parameter 'customField' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");

            var localVarPath = "/translations/{id}/custom/{customField}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (customField != null) localVarPathParams.Add("customField", this.Configuration.ApiClient.ParameterToString(customField)); // path parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsByIdFilterByCustomField", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>Dictionary<string, Dictionary<string, Object>></returns>
        public Dictionary<string, Dictionary<string, Object>> HttpTranslationsByIdFilterByProperty (string id, string property, bool? items = default(bool?))
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = HttpTranslationsByIdFilterByPropertyWithHttpInfo(id, property, items);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <returns>ApiResponse of Dictionary<string, Dictionary<string, Object>></returns>
        public ApiResponse<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByPropertyWithHttpInfo (string id, string property, bool? items = default(bool?))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            // verify the required parameter 'property' is set
            if (property == null)
                throw new ApiException(400, "Missing required parameter 'property' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");

            var localVarPath = "/translations/{id}/{property}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (property != null) localVarPathParams.Add("property", this.Configuration.ApiClient.ParameterToString(property)); // path parameter
            if (items != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "items", items)); // query parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsByIdFilterByProperty", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Dictionary<string, Dictionary<string, Object>></returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, Object>>> HttpTranslationsByIdFilterByPropertyAsync (string id, string property, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Dictionary<string, Dictionary<string, Object>>> localVarResponse = await HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync(id, property, items, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="AgravityPublic.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, Object>>>> HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync (string id, string property, bool? items = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            // verify the required parameter 'property' is set
            if (property == null)
                throw new ApiException(400, "Missing required parameter 'property' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");

            var localVarPath = "/translations/{id}/{property}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (property != null) localVarPathParams.Add("property", this.Configuration.ApiClient.ParameterToString(property)); // path parameter
            if (items != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "items", items)); // query parameter

            // authentication (function_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarHeaderParams["x-functions-key"] = this.Configuration.GetApiKeyWithPrefix("x-functions-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HttpTranslationsByIdFilterByProperty", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Dictionary<string, Object>>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Dictionary<string, Dictionary<string, Object>>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Dictionary<string, Object>>)));
        }

    }
}
