/*
 * Agravity OpenAPI Documentation - Public Functions
 *
 * <h1>Agravity API Reference</h1>This is the public API description of Agravity GmbH.<br/><h2>Resources</h2><ul> <li>Collection type management</li> <li>Collections management</li> <li>Assets management</li> <li>Assets operations</li> <li>Assets publishing</li> <li>Collection Sharing (consume share)</li> <li>Secure Upload (validate + upload file)</li> <li>Download ZIP</li> <li>Search</li> <li>General management</li></ul><h2> Operations</h2>Agravity API performs the following operations:<ul> <li>List / get single collection types</li> <li>List / get single collections</li> <li>List / get single  assets</li> <li>Operations on assets like: blobs, rotate, resize, similar, collections, customfields, download</li> <li>List / get single published asset</li> <li>Search for assets or collections</li> <li>Get version of deployment</li></ul><br/><b>API key is needed to access these endpoints.</b><br/><br/>Copyright © Agravity GmbH 2025. All Rights Reserved
 *
 * The version of the OpenAPI document: 8.4.0
 * Contact: office@agravity.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Agravity.Public.Client;
using Agravity.Public.Model;

namespace Agravity.Public.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicTranslationManagementApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        Dictionary<string, Dictionary<string, object>> HttpTranslationsById(string id, bool? items = default(bool?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdWithHttpInfo(string id, bool? items = default(bool?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        Dictionary<string, Dictionary<string, object>> HttpTranslationsByIdFilterByCustomField(string id, string customField, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfo(string id, string customField, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        Dictionary<string, Dictionary<string, object>> HttpTranslationsByIdFilterByProperty(string id, string property, bool? items = default(bool?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByPropertyWithHttpInfo(string id, string property, bool? items = default(bool?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicTranslationManagementApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdAsync(string id, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdWithHttpInfoAsync(string id, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByCustomFieldAsync(string id, string customField, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translation of custom field on the entity (Asset, Collection)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync(string id, string customField, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByPropertyAsync(string id, string property, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </remarks>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync(string id, string property, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPublicTranslationManagementApi : IPublicTranslationManagementApiSync, IPublicTranslationManagementApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PublicTranslationManagementApi : IPublicTranslationManagementApi
    {
        private Agravity.Public.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PublicTranslationManagementApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PublicTranslationManagementApi(string basePath)
        {
            this.Configuration = Agravity.Public.Client.Configuration.MergeConfigurations(
                Agravity.Public.Client.GlobalConfiguration.Instance,
                new Agravity.Public.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Agravity.Public.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Agravity.Public.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Agravity.Public.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PublicTranslationManagementApi(Agravity.Public.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Agravity.Public.Client.Configuration.MergeConfigurations(
                Agravity.Public.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Agravity.Public.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Agravity.Public.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Agravity.Public.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicTranslationManagementApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PublicTranslationManagementApi(Agravity.Public.Client.ISynchronousClient client, Agravity.Public.Client.IAsynchronousClient asyncClient, Agravity.Public.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Agravity.Public.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Agravity.Public.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Agravity.Public.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Agravity.Public.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Agravity.Public.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Dictionary<string, Dictionary<string, object>> HttpTranslationsById(string id, bool? items = default(bool?), int operationIndex = 0)
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = HttpTranslationsByIdWithHttpInfo(id, items);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdWithHttpInfo(string id, bool? items = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsById");
            }

            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (items != null)
            {
                localVarRequestOptions.QueryParameters.Add(Agravity.Public.Client.ClientUtils.ParameterToMultiMap("", "items", items));
            }

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Dictionary<string, object>>>("/translations/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdAsync(string id, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = await HttpTranslationsByIdWithHttpInfoAsync(id, items, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all the translations of a whole entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdWithHttpInfoAsync(string id, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsById");
            }


            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (items != null)
            {
                localVarRequestOptions.QueryParameters.Add(Agravity.Public.Client.ClientUtils.ParameterToMultiMap("", "items", items));
            }

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Dictionary<string, object>>>("/translations/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Dictionary<string, Dictionary<string, object>> HttpTranslationsByIdFilterByCustomField(string id, string customField, int operationIndex = 0)
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = HttpTranslationsByIdFilterByCustomFieldWithHttpInfo(id, customField);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfo(string id, string customField, int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            }

            // verify the required parameter 'customField' is set
            if (customField == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'customField' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            }

            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("customField", Agravity.Public.Client.ClientUtils.ParameterToString(customField)); // path parameter

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsByIdFilterByCustomField";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Dictionary<string, object>>>("/translations/{id}/custom/{customField}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsByIdFilterByCustomField", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByCustomFieldAsync(string id, string customField, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = await HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync(id, customField, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translation of custom field on the entity (Asset, Collection)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of only translateable entities with custom fields (Asset, Collection).</param>
        /// <param name="customField">Limit the output to a specific custom field key.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdFilterByCustomFieldWithHttpInfoAsync(string id, string customField, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            }

            // verify the required parameter 'customField' is set
            if (customField == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'customField' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByCustomField");
            }


            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("customField", Agravity.Public.Client.ClientUtils.ParameterToString(customField)); // path parameter

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsByIdFilterByCustomField";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Dictionary<string, object>>>("/translations/{id}/custom/{customField}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsByIdFilterByCustomField", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Dictionary<string, Dictionary<string, object>> HttpTranslationsByIdFilterByProperty(string id, string property, bool? items = default(bool?), int operationIndex = 0)
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = HttpTranslationsByIdFilterByPropertyWithHttpInfo(id, property, items);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByPropertyWithHttpInfo(string id, string property, bool? items = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            }

            // verify the required parameter 'property' is set
            if (property == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'property' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            }

            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("property", Agravity.Public.Client.ClientUtils.ParameterToString(property)); // path parameter
            if (items != null)
            {
                localVarRequestOptions.QueryParameters.Add(Agravity.Public.Client.ClientUtils.ParameterToMultiMap("", "items", items));
            }

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsByIdFilterByProperty";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Dictionary<string, object>>>("/translations/{id}/{property}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsByIdFilterByProperty", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, object>>> HttpTranslationsByIdFilterByPropertyAsync(string id, string property, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>> localVarResponse = await HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync(id, property, items, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the translations of a specific field on the entity (Asset, Collection, Collection Type, Download Format)
        /// </summary>
        /// <exception cref="Agravity.Public.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of any translateable entity (Asset, Collection, Collection Type, Download Format).</param>
        /// <param name="property">Limit to one specific property (key)</param>
        /// <param name="items">If the items should be included (only for entity type Collection and Asset). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, Object&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<Agravity.Public.Client.ApiResponse<Dictionary<string, Dictionary<string, object>>>> HttpTranslationsByIdFilterByPropertyWithHttpInfoAsync(string id, string property, bool? items = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'id' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            }

            // verify the required parameter 'property' is set
            if (property == null)
            {
                throw new Agravity.Public.Client.ApiException(400, "Missing required parameter 'property' when calling PublicTranslationManagementApi->HttpTranslationsByIdFilterByProperty");
            }


            Agravity.Public.Client.RequestOptions localVarRequestOptions = new Agravity.Public.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Agravity.Public.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Agravity.Public.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Agravity.Public.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("property", Agravity.Public.Client.ClientUtils.ParameterToString(property)); // path parameter
            if (items != null)
            {
                localVarRequestOptions.QueryParameters.Add(Agravity.Public.Client.ClientUtils.ParameterToMultiMap("", "items", items));
            }

            localVarRequestOptions.Operation = "PublicTranslationManagementApi.HttpTranslationsByIdFilterByProperty";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (function_key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-functions-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-functions-key", this.Configuration.GetApiKeyWithPrefix("x-functions-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Dictionary<string, object>>>("/translations/{id}/{property}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HttpTranslationsByIdFilterByProperty", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
