<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.0</TargetFrameworks>
		<AssemblyName>Agravity.Public</AssemblyName>
		<PackageId>Agravity.Public</PackageId>
		<OutputType>Library</OutputType>
		<Authors>PLO - Agravity GmbH</Authors>
		<Company>Agravity GmbH</Company>
		<AssemblyTitle>Agravity Public API library</AssemblyTitle>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageTags>
			microsoft;azure;cosmos;cosmosdb;documentdb;docdb;nosql;azureofficial;dotnetcore;netcore;netstandard
		</PackageTags>
		<Description>The Agravity Public API which is created via openapi-generator.</Description>
		<Copyright>Copyright Agravity GmbH</Copyright>
		<RootNamespace>Agravity.Public</RootNamespace>
		<Version>11.0.4</Version>
		<PackageProjectUrl>https://github.com/agravityio/agravity-public-csharp</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Agravity.Public.xml</DocumentationFile>
		<RepositoryUrl>https://github.com/agravityio/agravity-public-csharp</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReleaseNotes>
			The change log for this SDK is made available at
			https://github.com/agravityio/agravity-public-csharp/blob/main/README.md
			at the time of release.
		</PackageReleaseNotes>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugType>portable</DebugType>
		<IncludeSymbols>false</IncludeSymbols>
		<IncludeSource>false</IncludeSource>
		<RootNamespace>Agravity.Public</RootNamespace>
		<NoWarn>NU5125;MSB3245;MSB3243</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="JsonSubTypes" Version="2.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="RestSharp" Version="114.0.0" />
		<PackageReference Include="Polly" Version="8.6.6" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.Text.Json" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\icon.png" Pack="true" PackagePath="\" Link="icon.png" Visible="false" />
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Remove="System.Web" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.Web" />
	</ItemGroup>
</Project>