/*
 * Agravity OpenAPI Documentation - Public Functions
 *
 * <h1>Agravity API Reference</h1>This is the public API description of Agravity GmbH.<br/><h2>Resources</h2><ul> <li>Collection type management</li> <li>Collections management</li> <li>Assets management</li> <li>Assets operations</li> <li>Assets publishing</li> <li>Collection Sharing (consume share)</li> <li>Secure Upload (validate + upload file)</li> <li>Download ZIP</li> <li>Search</li> <li>General management</li></ul><h2> Operations</h2>Agravity API performs the following operations:<ul> <li>List / get single collection types</li> <li>List / get single collections</li> <li>List / get single  assets</li> <li>Operations on assets like: blobs, rotate, resize, similar, collections, customfields, download</li> <li>List / get single published asset</li> <li>Search for assets or collections</li> <li>Get version of deployment</li></ul><br/><b>API key is needed to access these endpoints.</b><br/><br/>Copyright © Agravity GmbH 2022. All Rights Reserved
 *
 * The version of the OpenAPI document: 4.7.1
 * Contact: office@agravity.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AgravityPublic.Client;
using AgravityPublic.Api;
using AgravityPublic.Model;

namespace AgravityPublic.Test
{
    /// <summary>
    ///  Class for testing PublicCollectionManagementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PublicCollectionManagementApiTests
    {
        private PublicCollectionManagementApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PublicCollectionManagementApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicCollectionManagementApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PublicCollectionManagementApi
            //Assert.IsInstanceOf(typeof(PublicCollectionManagementApi), instance);
        }

        
        /// <summary>
        /// Test HttpCollectionsCreate
        /// </summary>
        [Test]
        public void HttpCollectionsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectiontypeid = null;
            //Collection collection = null;
            //var response = instance.HttpCollectionsCreate(collectiontypeid, collection);
            //Assert.IsInstanceOf(typeof(Collection), response, "response is Collection");
        }
        
        /// <summary>
        /// Test HttpCollectionsGet
        /// </summary>
        [Test]
        public void HttpCollectionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collectiontypeid = null;
            //int? level = null;
            //string parentid = null;
            //string fields = null;
            //var response = instance.HttpCollectionsGet(collectiontypeid, level, parentid, fields);
            //Assert.IsInstanceOf(typeof(List<Collection>), response, "response is List<Collection>");
        }
        
        /// <summary>
        /// Test HttpCollectionsGetById
        /// </summary>
        [Test]
        public void HttpCollectionsGetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string fields = null;
            //var response = instance.HttpCollectionsGetById(id, fields);
            //Assert.IsInstanceOf(typeof(Collection), response, "response is Collection");
        }
        
        /// <summary>
        /// Test HttpCollectionsGetDescendantsTreeOfId
        /// </summary>
        [Test]
        public void HttpCollectionsGetDescendantsTreeOfIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.HttpCollectionsGetDescendantsTreeOfId(id);
            //Assert.IsInstanceOf(typeof(List<Collection>), response, "response is List<Collection>");
        }
        
        /// <summary>
        /// Test HttpCollectionsGetTreeAncestorsOfId
        /// </summary>
        [Test]
        public void HttpCollectionsGetTreeAncestorsOfIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.HttpCollectionsGetTreeAncestorsOfId(id);
            //Assert.IsInstanceOf(typeof(List<Collection>), response, "response is List<Collection>");
        }
        
        /// <summary>
        /// Test HttpGetCollectionPreviewsById
        /// </summary>
        [Test]
        public void HttpGetCollectionPreviewsByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.HttpGetCollectionPreviewsById(id);
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test HttpPublicCollectionsUpdateById
        /// </summary>
        [Test]
        public void HttpPublicCollectionsUpdateByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Collection collection = null;
            //var response = instance.HttpPublicCollectionsUpdateById(id, collection);
            //Assert.IsInstanceOf(typeof(Collection), response, "response is Collection");
        }
        
    }

}
